import type {
  FoodListing,
  LeaderboardEntry,
  ImpactMetrics,
  Notification,
} from './types';

// ─── Helper: hours from now as ISO string ────────────────────────────────────
const hoursFromNow = (h: number) =>
  new Date(Date.now() + h * 60 * 60 * 1000).toISOString();

const hoursAgo = (h: number) =>
  new Date(Date.now() - h * 60 * 60 * 1000).toISOString();

// ─── Food Listings ───────────────────────────────────────────────────────────
export const mockFoodListings: FoodListing[] = [
  {
    id: 'fl-001',
    title: 'Artisan Sourdough Loaves',
    description:
      'Freshly baked sourdough loaves from this morning. Crusty exterior, soft inside. Perfect for sandwiches or toast.',
    quantity: 12,
    unit: 'loaves',
    category: 'bakery',
    dietary_tags: ['vegan', 'dairy-free'],
    expiry_time: hoursFromNow(2),
    pickup_location: 'Flour Bakery, Colombo 03',
    pickup_lat: 6.9106,
    pickup_lng: 79.8553,
    image_url:
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
    donor_id: 'donor-001',
    donor_name: 'Flour Bakery',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=FB',
    status: 'available',
    priority_level: 'urgent',
    created_at: hoursAgo(1),
  },
  {
    id: 'fl-002',
    title: 'Garden Fresh Salad Bowls',
    description:
      'Mixed green salads with cherry tomatoes, cucumbers, and house vinaigrette. Individually packed.',
    quantity: 20,
    unit: 'bowls',
    category: 'prepared-meals',
    dietary_tags: ['vegan', 'gluten-free', 'nut-free'],
    expiry_time: hoursFromNow(3),
    pickup_location: 'The Gallery Cafe, Colombo 07',
    pickup_lat: 6.9147,
    pickup_lng: 79.8651,
    image_url:
      'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    donor_id: 'donor-002',
    donor_name: 'The Gallery Cafe',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=GC',
    status: 'available',
    priority_level: 'high',
    created_at: hoursAgo(2),
  },
  {
    id: 'fl-003',
    title: 'Club Sandwich Platters',
    description:
      'Assorted club sandwiches from the lunch buffet. Turkey, chicken, and vegetarian options available.',
    quantity: 15,
    unit: 'pieces',
    category: 'prepared-meals',
    dietary_tags: ['halal'],
    expiry_time: hoursFromNow(5),
    pickup_location: 'Hilton Colombo, Lotus Rd',
    pickup_lat: 6.9344,
    pickup_lng: 79.8428,
    image_url:
      'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=400&h=300&fit=crop',
    donor_id: 'donor-003',
    donor_name: 'Hilton Colombo',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=HC',
    status: 'available',
    priority_level: 'normal',
    created_at: hoursAgo(1),
  },
  {
    id: 'fl-004',
    title: 'Butter Croissants & Danish Pastries',
    description:
      "A mix of butter croissants, chocolate danish, and almond pastries from this morning's batch.",
    quantity: 30,
    unit: 'pieces',
    category: 'bakery',
    dietary_tags: ['vegetarian'],
    expiry_time: hoursFromNow(8),
    pickup_location: 'Barefoot Cafe, Colombo 03',
    pickup_lat: 6.9058,
    pickup_lng: 79.8553,
    image_url:
      'https://images.unsplash.com/photo-1517433367423-c7e5b0f35086?w=400&h=300&fit=crop',
    donor_id: 'donor-004',
    donor_name: 'Barefoot Cafe',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=BC',
    status: 'available',
    priority_level: 'normal',
    created_at: hoursAgo(3),
  },
  {
    id: 'fl-005',
    title: 'Seasonal Tropical Fruit Box',
    description:
      'Ripe mangoes, papayas, bananas, and pineapple. Sourced from local farmers, perfectly ripe.',
    quantity: 10,
    unit: 'kg',
    category: 'fruits-vegetables',
    dietary_tags: ['vegan', 'gluten-free', 'nut-free', 'dairy-free'],
    expiry_time: hoursFromNow(24),
    pickup_location: 'Green Path Organic, Colombo 07',
    pickup_lat: 6.9165,
    pickup_lng: 79.8636,
    image_url:
      'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=400&h=300&fit=crop',
    donor_id: 'donor-005',
    donor_name: 'Green Path Organic',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=GP',
    status: 'available',
    priority_level: 'normal',
    created_at: hoursAgo(4),
  },
  {
    id: 'fl-006',
    title: 'Sri Lankan Rice & Curry Set Meals',
    description:
      'Traditional rice and curry with dhal, fish curry, pol sambol, and papadam. Fully cooked and packed.',
    quantity: 25,
    unit: 'portions',
    category: 'prepared-meals',
    dietary_tags: ['halal', 'gluten-free'],
    expiry_time: hoursFromNow(1.5),
    pickup_location: 'Ministry of Crab, Dutch Hospital',
    pickup_lat: 6.9344,
    pickup_lng: 79.8440,
    image_url:
      'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400&h=300&fit=crop',
    donor_id: 'donor-006',
    donor_name: 'Ministry of Crab',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=MC',
    status: 'available',
    priority_level: 'urgent',
    created_at: hoursAgo(2),
  },
  {
    id: 'fl-007',
    title: 'Margherita & Veggie Pizza Slices',
    description:
      'Leftover pizza from a private event. Margherita and roasted vegetable varieties. Still warm!',
    quantity: 18,
    unit: 'slices',
    category: 'prepared-meals',
    dietary_tags: ['vegetarian'],
    expiry_time: hoursFromNow(4),
    pickup_location: 'Cargills FoodCity, Colombo 04',
    pickup_lat: 6.8967,
    pickup_lng: 79.8573,
    image_url:
      'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop',
    donor_id: 'donor-007',
    donor_name: 'Cargills FoodCity',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=CF',
    status: 'available',
    priority_level: 'high',
    created_at: hoursAgo(1),
  },
  {
    id: 'fl-008',
    title: 'Steamed Basmati Rice Packs',
    description:
      'Perfectly cooked basmati rice in 500g packs. Ideal for pairing with curry or stir-fry.',
    quantity: 15,
    unit: 'packs',
    category: 'prepared-meals',
    dietary_tags: ['vegan', 'gluten-free', 'halal', 'kosher'],
    expiry_time: hoursFromNow(6),
    pickup_location: 'Keells Super, Union Place',
    pickup_lat: 6.9188,
    pickup_lng: 79.8577,
    image_url:
      'https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?w=400&h=300&fit=crop',
    donor_id: 'donor-008',
    donor_name: 'Keells Super',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=KS',
    status: 'available',
    priority_level: 'normal',
    created_at: hoursAgo(3),
  },
  {
    id: 'fl-009',
    title: 'Organic Vegetable Medley',
    description:
      'Assorted organic vegetables — carrots, beans, bell peppers, and spinach. Great for meal prep.',
    quantity: 8,
    unit: 'kg',
    category: 'fruits-vegetables',
    dietary_tags: ['vegan', 'gluten-free', 'nut-free', 'dairy-free'],
    expiry_time: hoursFromNow(48),
    pickup_location: 'Good Market, Colombo 07',
    pickup_lat: 6.9125,
    pickup_lng: 79.8610,
    image_url:
      'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=300&fit=crop',
    donor_id: 'donor-009',
    donor_name: 'Good Market Colombo',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=GM',
    status: 'available',
    priority_level: 'normal',
    created_at: hoursAgo(6),
  },
  {
    id: 'fl-010',
    title: 'Fresh-Pressed Juice Bottles',
    description:
      'Cold-pressed orange, watermelon, and green detox juices. 350ml bottles, made this morning.',
    quantity: 24,
    unit: 'bottles',
    category: 'beverages',
    dietary_tags: ['vegan', 'gluten-free', 'dairy-free'],
    expiry_time: hoursFromNow(10),
    pickup_location: 'Juice Bar, Park Street',
    pickup_lat: 6.9103,
    pickup_lng: 79.8540,
    image_url:
      'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?w=400&h=300&fit=crop',
    donor_id: 'donor-010',
    donor_name: 'The Juice Bar',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=JB',
    status: 'available',
    priority_level: 'normal',
    created_at: hoursAgo(2),
  },
  {
    id: 'fl-011',
    title: 'Celebration Cake Slices',
    description:
      'Leftover chocolate and vanilla cake slices from a corporate event. Beautifully decorated.',
    quantity: 16,
    unit: 'slices',
    category: 'snacks',
    dietary_tags: ['vegetarian'],
    expiry_time: hoursFromNow(12),
    pickup_location: 'Shangri-La Colombo, Galle Face',
    pickup_lat: 6.9286,
    pickup_lng: 79.8440,
    image_url:
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
    donor_id: 'donor-011',
    donor_name: 'Shangri-La Colombo',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=SL',
    status: 'available',
    priority_level: 'normal',
    created_at: hoursAgo(4),
  },
  {
    id: 'fl-012',
    title: 'Sushi & Maki Rolls Assortment',
    description:
      'Premium sushi platter with salmon nigiri, tuna maki, and vegetable rolls. Refrigerated.',
    quantity: 40,
    unit: 'pieces',
    category: 'prepared-meals',
    dietary_tags: ['gluten-free', 'dairy-free'],
    expiry_time: hoursFromNow(2.5),
    pickup_location: 'Nihonbashi, Colombo 03',
    pickup_lat: 6.9120,
    pickup_lng: 79.8520,
    image_url:
      'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&h=300&fit=crop',
    donor_id: 'donor-012',
    donor_name: 'Nihonbashi',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=NB',
    status: 'available',
    priority_level: 'urgent',
    created_at: hoursAgo(1),
  },
  {
    id: 'fl-013',
    title: 'Hearty Vegetable Soup',
    description:
      'Homestyle vegetable soup with lentils, potatoes, and carrots. Packed in 500ml containers.',
    quantity: 10,
    unit: 'containers',
    category: 'prepared-meals',
    dietary_tags: ['vegan', 'halal', 'nut-free'],
    expiry_time: hoursFromNow(5),
    pickup_location: 'Commons Coffee House, Colombo 07',
    pickup_lat: 6.9152,
    pickup_lng: 79.8669,
    image_url:
      'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop',
    donor_id: 'donor-013',
    donor_name: 'Commons Coffee House',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=CC',
    status: 'available',
    priority_level: 'normal',
    created_at: hoursAgo(3),
  },
  {
    id: 'fl-014',
    title: 'Gourmet Beef Burgers',
    description:
      'Wagyu beef patties with caramelised onions, cheddar, and brioche buns. From today\'s lunch service.',
    quantity: 8,
    unit: 'burgers',
    category: 'prepared-meals',
    dietary_tags: ['halal'],
    expiry_time: hoursFromNow(3),
    pickup_location: 'The Lagoon, Cinnamon Grand',
    pickup_lat: 6.9175,
    pickup_lng: 79.8488,
    image_url:
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=300&fit=crop',
    donor_id: 'donor-014',
    donor_name: 'Cinnamon Grand',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=CG',
    status: 'available',
    priority_level: 'high',
    created_at: hoursAgo(1),
  },
  {
    id: 'fl-015',
    title: 'Veggie Wraps & Falafel',
    description:
      'Mediterranean-style falafel wraps with hummus, lettuce, and tahini sauce. Ready to eat.',
    quantity: 14,
    unit: 'wraps',
    category: 'prepared-meals',
    dietary_tags: ['vegan', 'halal', 'dairy-free'],
    expiry_time: hoursFromNow(7),
    pickup_location: 'Cafe Kumbuk, Colombo 07',
    pickup_lat: 6.9133,
    pickup_lng: 79.8630,
    image_url:
      'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=400&h=300&fit=crop',
    donor_id: 'donor-015',
    donor_name: 'Cafe Kumbuk',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=CK',
    status: 'available',
    priority_level: 'normal',
    created_at: hoursAgo(2),
  },
  {
    id: 'fl-016',
    title: 'Fresh Dairy Yoghurt Cups',
    description:
      'Natural set yoghurt in 200g cups. Plain and fruit-flavoured varieties. Near best-before date.',
    quantity: 20,
    unit: 'cups',
    category: 'dairy',
    dietary_tags: ['vegetarian', 'gluten-free', 'nut-free'],
    expiry_time: hoursFromNow(36),
    pickup_location: 'Keells Super, Crescat Boulevard',
    pickup_lat: 6.9170,
    pickup_lng: 79.8485,
    image_url:
      'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop',
    donor_id: 'donor-008',
    donor_name: 'Keells Super',
    donor_avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=KS',
    status: 'available',
    priority_level: 'normal',
    created_at: hoursAgo(8),
  },
];

// ─── Leaderboard ─────────────────────────────────────────────────────────────
export const mockLeaderboard: LeaderboardEntry[] = [
  {
    id: 'lb-001',
    name: 'Hilton Colombo',
    avatar_url: 'https://api.dicebear.com/9.x/initials/svg?seed=HC',
    role: 'business',
    score: 9850,
    food_donated_kg: 342,
    meals_provided: 855,
    badges: ['eco-hero', 'community-champion', 'monthly-master'],
    rank: 1,
  },
  {
    id: 'lb-002',
    name: 'Cargills FoodCity',
    avatar_url: 'https://api.dicebear.com/9.x/initials/svg?seed=CF',
    role: 'business',
    score: 8720,
    food_donated_kg: 298,
    meals_provided: 745,
    badges: ['eco-hero', 'food-saver', 'weekly-warrior'],
    rank: 2,
  },
  {
    id: 'lb-003',
    name: 'Keells Super',
    avatar_url: 'https://api.dicebear.com/9.x/initials/svg?seed=KS',
    role: 'business',
    score: 7650,
    food_donated_kg: 263,
    meals_provided: 658,
    badges: ['eco-hero', 'food-saver'],
    rank: 3,
  },
  {
    id: 'lb-004',
    name: 'Amara Silva',
    avatar_url: 'https://api.dicebear.com/9.x/initials/svg?seed=AS',
    role: 'volunteer',
    score: 6200,
    food_donated_kg: 0,
    meals_provided: 420,
    badges: ['community-champion', 'weekly-warrior'],
    rank: 4,
  },
  {
    id: 'lb-005',
    name: 'Ministry of Crab',
    avatar_url: 'https://api.dicebear.com/9.x/initials/svg?seed=MC',
    role: 'business',
    score: 5800,
    food_donated_kg: 195,
    meals_provided: 488,
    badges: ['food-saver', 'first-donation'],
    rank: 5,
  },
  {
    id: 'lb-006',
    name: 'Salvation Army LK',
    avatar_url: 'https://api.dicebear.com/9.x/initials/svg?seed=SA',
    role: 'charity',
    score: 5400,
    food_donated_kg: 0,
    meals_provided: 1250,
    badges: ['community-champion', 'monthly-master'],
    rank: 6,
  },
  {
    id: 'lb-007',
    name: 'Flour Bakery',
    avatar_url: 'https://api.dicebear.com/9.x/initials/svg?seed=FB',
    role: 'business',
    score: 4900,
    food_donated_kg: 167,
    meals_provided: 418,
    badges: ['food-saver', 'weekly-warrior'],
    rank: 7,
  },
  {
    id: 'lb-008',
    name: 'Dinesh Perera',
    avatar_url: 'https://api.dicebear.com/9.x/initials/svg?seed=DP',
    role: 'volunteer',
    score: 4350,
    food_donated_kg: 0,
    meals_provided: 310,
    badges: ['weekly-warrior', 'first-donation'],
    rank: 8,
  },
  {
    id: 'lb-009',
    name: 'The Gallery Cafe',
    avatar_url: 'https://api.dicebear.com/9.x/initials/svg?seed=GC',
    role: 'business',
    score: 3800,
    food_donated_kg: 132,
    meals_provided: 330,
    badges: ['food-saver'],
    rank: 9,
  },
  {
    id: 'lb-010',
    name: 'Priya Jayawardena',
    avatar_url: 'https://api.dicebear.com/9.x/initials/svg?seed=PJ',
    role: 'public',
    score: 3200,
    food_donated_kg: 45,
    meals_provided: 113,
    badges: ['first-donation', 'weekly-warrior'],
    rank: 10,
  },
];

// ─── Impact Metrics ──────────────────────────────────────────────────────────
export const mockImpactMetrics: ImpactMetrics = {
  food_saved_kg: 12847,
  meals_provided: 32118,
  co2_saved_kg: 45992,
  money_saved: 109200,
  active_donors: 186,
  active_volunteers: 94,
};

// ─── Notifications ───────────────────────────────────────────────────────────
export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    user_id: 'user-001',
    title: 'New Claim on Your Listing',
    message:
      'Salvation Army LK has claimed your "Artisan Sourdough Loaves" listing. Please confirm pickup.',
    type: 'claim',
    read: false,
    created_at: hoursAgo(0.5),
  },
  {
    id: 'notif-002',
    user_id: 'user-001',
    title: 'Listing Expiring Soon',
    message:
      'Your "Sri Lankan Rice & Curry Set Meals" listing expires in 1.5 hours. Consider reducing quantity or extending.',
    type: 'expiry',
    read: false,
    created_at: hoursAgo(1),
  },
  {
    id: 'notif-003',
    user_id: 'user-001',
    title: 'Badge Earned: Food Saver! 🍽️',
    message:
      'Congratulations! You\'ve rescued over 50 meals and earned the "Food Saver" badge.',
    type: 'achievement',
    read: false,
    created_at: hoursAgo(3),
  },
  {
    id: 'notif-004',
    user_id: 'user-001',
    title: 'Donation Received',
    message:
      'Thank you! Your "Butter Croissants & Danish Pastries" has been successfully collected by Amara Silva.',
    type: 'donation',
    read: true,
    created_at: hoursAgo(5),
  },
  {
    id: 'notif-005',
    user_id: 'user-001',
    title: 'New Food Available Nearby',
    message:
      'Nihonbashi just listed "Sushi & Maki Rolls Assortment" 1.2 km from your location.',
    type: 'donation',
    read: true,
    created_at: hoursAgo(6),
  },
  {
    id: 'notif-006',
    user_id: 'user-001',
    title: 'Pickup Confirmed',
    message:
      'Your claim on "Garden Fresh Salad Bowls" from The Gallery Cafe has been confirmed for pickup.',
    type: 'claim',
    read: true,
    created_at: hoursAgo(8),
  },
  {
    id: 'notif-007',
    user_id: 'user-001',
    title: 'Weekly Impact Summary',
    message:
      'This week, the RePlate community saved 487 kg of food and provided 1,218 meals. You contributed 12 kg!',
    type: 'achievement',
    read: true,
    created_at: hoursAgo(24),
  },
  {
    id: 'notif-008',
    user_id: 'user-001',
    title: 'Listing Expired',
    message:
      'Your "Grilled Chicken Wraps" listing has expired and was automatically removed.',
    type: 'expiry',
    read: true,
    created_at: hoursAgo(30),
  },
];
